### ISSUE TITLE
Youtube anddea video buffering 

### ISSUE THREAD

**Issue by aravindk64** [revanced-apks/build-apps#116]
While playing the video it stops and buffers the video for endless
![Screenshot_20240401-084622](https://github.com/revanced-apks/build-apps/assets/55388457/4b211f49-e380-4232-a2b2-8081b2c46bb1)

**Comment by rabilrbl** [comment]
It should be fixed in latest release

Feel free to re open

**Comment by aravindk64** [comment]
> It should be fixed in latest release
> 
> Feel free to re open

I'm use the lastest version only still the issue is not resolved.
